Update harness.py
PythonFuzz passes in a bytes object but vyper is expecting a str. When running the harness as is coverage gets halted at:

/myenv/lib/python3.10/site-packages/vyper/ast/utils.py", line 29, in parse_to_ast
    if "\x00" in source_code:
TypeError: a bytes-like object is required, not 'str'